In [9]:
pip install numpy

   ---------------------------------------- 0.0/12.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.5 MB ? eta -:--:--
    --------------------------------------- 0.3/12.5 MB ? eta -:--:--
    --------------------------------------- 0.3/12.5 MB ? eta -:--:--
   - -------------------------------------- 0.5/12.5 MB 621.2 kB/s eta 0:00:20
   -- ------------------------------------- 0.8/12.5 MB 1.2 MB/s eta 0:00:10
   --- ------------------------------------ 1.0/12.5 MB 949.8 kB/s eta 0:00:13
   --- ------------------------------------ 1.0/12.5 MB 949.8 kB/s eta 0:00:13
   ----- ---------------------------------- 1.6/12.5 MB 1.2 MB/s eta 0:00:10
   ------- -------------------------------- 2.4/12.5 MB 1.5 MB/s eta 0:00:07
   ----------- ---------------------------- 3.7/12.5 MB 2.0 MB/s eta 0:00:05
   ----------------- ---------------------- 5.5/12.5 MB 2.8 MB/s eta 0:00:03
   ---------------------- ----------------- 7.1/12.5 MB 3.3 MB/s eta 0:00:02
   ------------------


[notice] A new release of pip is available: 25.0.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [10]:
import numpy as np

a = np.array([[1, 2, 3],
              [4, 5, 6]])
a.shape


(2, 3)

In [11]:
a = np.array([1, 2, 3, 4, 5, 6])
a

array([1, 2, 3, 4, 5, 6])

In [12]:
a[0]

np.int64(1)

In [13]:
a[0] = 10
a

array([10,  2,  3,  4,  5,  6])

In [14]:
a[:3]

array([10,  2,  3])

In [15]:
b = a[3:]
b

array([4, 5, 6])

In [16]:
b[0] = 40
a

array([10,  2,  3, 40,  5,  6])

In [23]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [24]:
a[1, 3]

np.int64(8)